-- Migration: Create feedback_submissions table
-- Purpose: Store feedback responses from users on the landing page
-- Created: 2026-04-12

CREATE TABLE IF NOT EXISTS public.feedback_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL,
  type text NOT NULL DEFAULT 'General Feedback',
  feedback text NOT NULL,
  created_at timestamptz DEFAULT now()
);

-- Add RLS policy to allow anonymous inserts (landing page feedback)
ALTER TABLE public.feedback_submissions ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert feedback (unauthenticated)
CREATE POLICY "Allow anonymous feedback submission" ON public.feedback_submissions
  FOR INSERT
  WITH CHECK (true);

-- Allow authenticated users to view their own feedback
CREATE POLICY "Allow users to view own feedback" ON public.feedback_submissions
  FOR SELECT
  USING (auth.email() = email);

-- Create index for performance
CREATE INDEX IF NOT EXISTS feedback_submissions_email_idx ON public.feedback_submissions(email);
CREATE INDEX IF NOT EXISTS feedback_submissions_created_at_idx ON public.feedback_submissions(created_at);

-- ============================================================
-- Fix contact_submissions RLS policies if table exists
-- ============================================================
DROP POLICY IF EXISTS "Allow anonymous contact submission" ON public.contact_submissions;
DROP POLICY IF EXISTS "Allow users to view own contact" ON public.contact_submissions;

CREATE POLICY "Allow anonymous contact submission" ON public.contact_submissions
  FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow users to view own contact" ON public.contact_submissions
  FOR SELECT
  USING (auth.email() = email);
